parameters:
#    dualize_user_search.example.class: Dualize\UserSearchBundle\Example

services:
#    dualize_user_search.example:
#        class: %dualize_user_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    # Add custom field, where city id is converted to city object
    dualize_user_search.search.sociotype_selector:
        class: Dualize\UserSearchBundle\Form\Field\SociotypeSelectorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: sociotype_selector }