parameters:
#    dualize_bb_code.example.class: Dualize\BBCodeBundle\Example

services:
#    dualize_bb_code.example:
#        class: %dualize_bb_code.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    dualize_bb_code.twig.dualize_bbcode:
        class: Dualize\BBCodeBundle\Twig\BBCodeExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }
