parameters:
#    dualize_socio.example.class: Dualize\SocioBundle\Example

services:
#    dualize_socio.example:
#        class: %dualize_socio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
